// ─── Craft Model Registry ──────────────────────────────────────────────────────
// All AI generation models available in Hypnotic Craft
// Each model has rich metadata for the model selector UI

export type ModelType = 'image' | 'video' | 'audio' | 'voice' | 'music';
export type ModelTier = 'fast' | 'quality' | 'ultra';
export type ModelProvider =
  | 'fal' | 'replicate' | 'runway' | 'kling' | 'wan' | 'hailuo' | 'seedance'
  | 'openai' | 'google' | 'stability' | 'suno' | 'elevenlabs' | 'ideogram'
  | 'recraft' | 'qwen' | 'grok' | 'reve' | 'mystic' | 'seedream' | 'zimage';

export interface CraftModel {
  id: string;
  name: string;
  provider: ModelProvider;
  type: ModelType;
  tier: ModelTier;
  badge?: string;                   // e.g. "New", "Recommended", "Best Value"
  description: string;
  keyFeatures: string[];
  maxResolution?: string;
  maxDuration?: number;             // seconds for video/audio
  nativeAudio?: boolean;
  lipSync?: boolean;
  firstFrame?: boolean;
  lastFrame?: boolean;
  motionControl?: boolean;
  realisticOutput?: boolean;
  styleControl?: boolean;
  imageToVideo?: boolean;
  textToVideo?: boolean;
  credits: number;                  // credits per generation
  isRecommended?: boolean;
  isNew?: boolean;
  capabilities: string[];
}

// ─── IMAGE MODELS ──────────────────────────────────────────────────────────────

export const IMAGE_MODELS: CraftModel[] = [
  {
    id: 'flux-2-pro',
    name: 'Flux.2 Pro',
    provider: 'fal',
    type: 'image',
    tier: 'ultra',
    badge: 'Recommended',
    description: 'Best-in-class photorealism with exceptional prompt adherence and detail.',
    keyFeatures: ['Photorealistic', 'High detail', 'Prompt fidelity', '4K output'],
    maxResolution: '4096×4096',
    realisticOutput: true,
    styleControl: true,
    credits: 8,
    isRecommended: true,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'flux-2-max',
    name: 'Flux.2 Max',
    provider: 'fal',
    type: 'image',
    tier: 'ultra',
    description: 'Maximum quality flagship model. Slow but exceptional for hero visuals.',
    keyFeatures: ['Maximum quality', 'Ultra detail', 'Complex scenes', 'Commercial grade'],
    maxResolution: '4096×4096',
    realisticOutput: true,
    styleControl: true,
    credits: 12,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'flux-2-flex',
    name: 'Flux.2 Flex',
    provider: 'fal',
    type: 'image',
    tier: 'quality',
    description: 'Flexible generation with strong style transfer and creative control.',
    keyFeatures: ['Style transfer', 'Creative control', 'Reference images', 'Fast'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'image-to-image', 'style-control'],
  },
  {
    id: 'flux-1-kontext-max',
    name: 'Flux.1 Kontext Max',
    provider: 'fal',
    type: 'image',
    tier: 'ultra',
    badge: 'New',
    description: 'Context-aware generation with advanced scene understanding.',
    keyFeatures: ['Context-aware', 'Scene coherence', 'Multi-element', 'Editorial'],
    maxResolution: '4096×4096',
    styleControl: true,
    credits: 10,
    isNew: true,
    capabilities: ['text-to-image', 'context-aware'],
  },
  {
    id: 'flux-1-kontext-pro',
    name: 'Flux.1 Kontext Pro',
    provider: 'fal',
    type: 'image',
    tier: 'quality',
    description: 'Professional context-aware model balancing quality and speed.',
    keyFeatures: ['Context-aware', 'Professional', 'Balanced speed', 'Consistent'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 6,
    capabilities: ['text-to-image', 'context-aware'],
  },
  {
    id: 'flux-2-klein',
    name: 'Flux.2 Klein',
    provider: 'fal',
    type: 'image',
    tier: 'fast',
    description: 'Compact fast model for rapid iteration and concept exploration.',
    keyFeatures: ['Ultra fast', 'Low cost', 'Rapid iteration', 'Good quality'],
    maxResolution: '1024×1024',
    credits: 2,
    capabilities: ['text-to-image'],
  },
  {
    id: 'flux-1',
    name: 'Flux.1',
    provider: 'fal',
    type: 'image',
    tier: 'quality',
    description: 'Classic FLUX model. Reliable, high-quality, proven performance.',
    keyFeatures: ['Reliable', 'High quality', 'Well-tested', 'Versatile'],
    maxResolution: '2048×2048',
    credits: 4,
    capabilities: ['text-to-image'],
  },
  {
    id: 'flux-1-fast',
    name: 'Flux.1 Fast',
    provider: 'fal',
    type: 'image',
    tier: 'fast',
    description: 'Optimized FLUX for speed without sacrificing too much quality.',
    keyFeatures: ['Fast', 'Cost-effective', 'Good quality', 'Batch-friendly'],
    maxResolution: '1024×1024',
    credits: 2,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-nano-banana-2',
    name: 'Google Nano Banana 2',
    provider: 'google',
    type: 'image',
    tier: 'quality',
    badge: 'New',
    description: 'Google\'s latest compact model with strong coherence and realism.',
    keyFeatures: ['Google quality', 'Fast', 'Coherent', 'Photorealistic'],
    maxResolution: '2048×2048',
    realisticOutput: true,
    credits: 4,
    isNew: true,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-nano-banana-pro',
    name: 'Google Nano Banana Pro',
    provider: 'google',
    type: 'image',
    tier: 'ultra',
    description: 'Pro tier Google model with enhanced detail and photorealism.',
    keyFeatures: ['Enhanced detail', 'Pro quality', 'Complex prompts', 'Google AI'],
    maxResolution: '4096×4096',
    realisticOutput: true,
    credits: 8,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-nano-banana',
    name: 'Google Nano Banana',
    provider: 'google',
    type: 'image',
    tier: 'fast',
    description: 'Lightweight Google model for fast concept generation.',
    keyFeatures: ['Fast', 'Lightweight', 'Cost-effective', 'Consistent'],
    maxResolution: '1024×1024',
    credits: 2,
    capabilities: ['text-to-image'],
  },
  {
    id: 'seedream-5-lite',
    name: 'Seedream 5 Lite',
    provider: 'seedream',
    type: 'image',
    tier: 'fast',
    description: 'Lightweight version of Seedream 5 for quick iterations.',
    keyFeatures: ['Fast', 'Creative', 'Stylized', 'Good aesthetics'],
    maxResolution: '1024×1024',
    styleControl: true,
    credits: 2,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'seedream-4',
    name: 'Seedream 4',
    provider: 'seedream',
    type: 'image',
    tier: 'quality',
    description: 'Seedream 4 with strong aesthetic and creative generation.',
    keyFeatures: ['Aesthetic', 'Creative', 'Style-forward', 'Consistent'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 4,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'seedream-4-4k',
    name: 'Seedream 4 4K',
    provider: 'seedream',
    type: 'image',
    tier: 'ultra',
    description: 'Seedream 4 in 4K for high-resolution production assets.',
    keyFeatures: ['4K output', 'Production grade', 'High detail', 'Aesthetic'],
    maxResolution: '4096×4096',
    styleControl: true,
    credits: 8,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'seedream-4-5',
    name: 'Seedream 4.5',
    provider: 'seedream',
    type: 'image',
    tier: 'quality',
    badge: 'New',
    description: 'Latest Seedream with enhanced aesthetic intelligence.',
    keyFeatures: ['Enhanced aesthetics', 'Better composition', 'Style control', 'Fast'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    isNew: true,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'mystic-2-5',
    name: 'Mystic 2.5',
    provider: 'mystic',
    type: 'image',
    tier: 'quality',
    description: 'Mystic 2.5 — balanced quality and speed with strong artistic range.',
    keyFeatures: ['Artistic', 'Balanced', 'Good detail', 'Versatile'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'mystic-2-5-flexible',
    name: 'Mystic 2.5 Flexible',
    provider: 'mystic',
    type: 'image',
    tier: 'quality',
    description: 'Flexible variant with image-to-image and style transfer capabilities.',
    keyFeatures: ['Image-to-image', 'Style transfer', 'Inpainting', 'Flexible'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'image-to-image', 'style-control'],
  },
  {
    id: 'mystic-2-5-fluid',
    name: 'Mystic 2.5 Fluid',
    provider: 'mystic',
    type: 'image',
    tier: 'quality',
    description: 'Fluid variant optimized for smooth, flowing compositions.',
    keyFeatures: ['Fluid compositions', 'Natural results', 'Organic', 'Editorial'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'mystic-1-0',
    name: 'Mystic 1.0',
    provider: 'mystic',
    type: 'image',
    tier: 'fast',
    description: 'Original Mystic model — fast, reliable for concept exploration.',
    keyFeatures: ['Fast', 'Reliable', 'Concept generation', 'Low cost'],
    maxResolution: '1024×1024',
    credits: 3,
    capabilities: ['text-to-image'],
  },
  {
    id: 'gpt-1-hq',
    name: 'GPT 1 - HQ',
    provider: 'openai',
    type: 'image',
    tier: 'quality',
    description: 'OpenAI GPT-based image generation with instruction following.',
    keyFeatures: ['Instruction following', 'Text rendering', 'Complex prompts', 'Consistent'],
    maxResolution: '2048×2048',
    credits: 6,
    capabilities: ['text-to-image'],
  },
  {
    id: 'gpt-1-5',
    name: 'GPT 1.5',
    provider: 'openai',
    type: 'image',
    tier: 'quality',
    badge: 'New',
    description: 'GPT 1.5 — improved prompt adherence and image quality.',
    keyFeatures: ['Better quality', 'Text rendering', 'Creative', 'Fast'],
    maxResolution: '2048×2048',
    credits: 6,
    isNew: true,
    capabilities: ['text-to-image'],
  },
  {
    id: 'gpt-1-5-high',
    name: 'GPT 1.5 - High',
    provider: 'openai',
    type: 'image',
    tier: 'ultra',
    description: 'GPT 1.5 in high quality mode for premium production use.',
    keyFeatures: ['Maximum quality', 'High detail', 'Premium output', 'Text rendering'],
    maxResolution: '4096×4096',
    credits: 10,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-imagen-3',
    name: 'Google Imagen 3',
    provider: 'google',
    type: 'image',
    tier: 'quality',
    description: 'Google Imagen 3 — strong photorealism and prompt understanding.',
    keyFeatures: ['Photorealistic', 'Strong comprehension', 'Google quality', 'Reliable'],
    maxResolution: '2048×2048',
    realisticOutput: true,
    credits: 6,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-imagen-4',
    name: 'Google Imagen 4',
    provider: 'google',
    type: 'image',
    tier: 'ultra',
    badge: 'New',
    description: 'Imagen 4 — Google\'s latest flagship with exceptional photorealism.',
    keyFeatures: ['Exceptional realism', 'Next-gen quality', 'Complex scenes', 'Consistent'],
    maxResolution: '4096×4096',
    realisticOutput: true,
    credits: 10,
    isNew: true,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-imagen-4-fast',
    name: 'Google Imagen 4 Fast',
    provider: 'google',
    type: 'image',
    tier: 'fast',
    description: 'Imagen 4 optimized for speed — great quality at 3x faster.',
    keyFeatures: ['Fast Imagen 4', 'Good quality', 'Cost-effective', 'Consistent'],
    maxResolution: '1024×1024',
    realisticOutput: true,
    credits: 4,
    capabilities: ['text-to-image'],
  },
  {
    id: 'google-imagen-4-ultra',
    name: 'Google Imagen 4 Ultra',
    provider: 'google',
    type: 'image',
    tier: 'ultra',
    badge: 'Best Quality',
    description: 'The pinnacle of Google image generation. Ultra-high fidelity.',
    keyFeatures: ['Ultra fidelity', 'Photo-perfect', 'Max detail', 'Production ready'],
    maxResolution: '8192×8192',
    realisticOutput: true,
    credits: 16,
    capabilities: ['text-to-image'],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    provider: 'ideogram',
    type: 'image',
    tier: 'quality',
    description: 'Best-in-class text rendering within images. Typography and logos.',
    keyFeatures: ['Best text rendering', 'Typography', 'Logos', 'Design-forward'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'text-rendering'],
  },
  {
    id: 'recraft-v4',
    name: 'Recraft V4',
    provider: 'recraft',
    type: 'image',
    tier: 'quality',
    description: 'Design-focused model with exceptional style consistency.',
    keyFeatures: ['Design focused', 'Style consistent', 'Brand-safe', 'Professional'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'recraft-v4-pro',
    name: 'Recraft V4 Pro',
    provider: 'recraft',
    type: 'image',
    tier: 'ultra',
    description: 'Pro version with vector output and advanced style controls.',
    keyFeatures: ['Vector output', 'Brand kits', 'Style library', 'Pro grade'],
    maxResolution: '4096×4096',
    styleControl: true,
    credits: 8,
    capabilities: ['text-to-image', 'style-control', 'vector'],
  },
  {
    id: 'reve',
    name: 'Reve',
    provider: 'reve',
    type: 'image',
    tier: 'quality',
    description: 'Cinematic, editorial quality with dramatic lighting and composition.',
    keyFeatures: ['Cinematic', 'Editorial', 'Dramatic lighting', 'Film-like'],
    maxResolution: '2048×2048',
    styleControl: true,
    credits: 5,
    capabilities: ['text-to-image', 'style-control'],
  },
  {
    id: 'qwen',
    name: 'Qwen',
    provider: 'qwen',
    type: 'image',
    tier: 'quality',
    description: 'Strong Asian aesthetic and cultural scene understanding.',
    keyFeatures: ['Asian aesthetics', 'Cultural accuracy', 'Detailed', 'Versatile'],
    maxResolution: '2048×2048',
    credits: 4,
    capabilities: ['text-to-image'],
  },
  {
    id: 'grok',
    name: 'Grok',
    provider: 'grok',
    type: 'image',
    tier: 'quality',
    description: 'xAI\'s image model with creative interpretation and humor.',
    keyFeatures: ['Creative', 'Unique style', 'Strong concepts', 'Fast'],
    maxResolution: '2048×2048',
    credits: 4,
    capabilities: ['text-to-image'],
  },
  {
    id: 'z-image',
    name: 'Z-Image',
    provider: 'zimage',
    type: 'image',
    tier: 'quality',
    description: 'High-fidelity generation with strong compositional intelligence.',
    keyFeatures: ['Compositional AI', 'High fidelity', 'Balanced', 'Consistent'],
    maxResolution: '2048×2048',
    credits: 5,
    capabilities: ['text-to-image'],
  },
];

// ─── VIDEO MODELS ──────────────────────────────────────────────────────────────

export const VIDEO_MODELS: CraftModel[] = [
  {
    id: 'auto',
    name: 'Auto (Recommended)',
    provider: 'kling',
    type: 'video',
    tier: 'quality',
    badge: 'Auto',
    description: 'Hypnotic selects the best model for your content automatically.',
    keyFeatures: ['Smart routing', 'Best for content', 'Always optimal', 'Cost-efficient'],
    maxDuration: 12,
    nativeAudio: false,
    firstFrame: true,
    lastFrame: true,
    motionControl: true,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 10,
    isRecommended: true,
    capabilities: ['text-to-video', 'image-to-video', 'auto-routing'],
  },
  {
    id: 'kling-2-6',
    name: 'Kling 2.6',
    provider: 'kling',
    type: 'video',
    tier: 'ultra',
    badge: 'Best Motion',
    description: 'Kling 2.6 — state-of-the-art motion quality and character consistency.',
    keyFeatures: ['Best motion quality', 'Character consistency', '5s / 10s', 'First + Last frame'],
    maxDuration: 10,
    nativeAudio: true,
    lipSync: false,
    firstFrame: true,
    lastFrame: true,
    motionControl: true,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 15,
    capabilities: ['text-to-video', 'image-to-video', 'motion-control'],
  },
  {
    id: 'wan',
    name: 'Wan',
    provider: 'wan',
    type: 'video',
    tier: 'quality',
    description: 'Wan video model — strong consistency for character-driven scenes.',
    keyFeatures: ['Character consistency', 'Stable motion', 'Cost-effective', '5s clips'],
    maxDuration: 5,
    firstFrame: true,
    motionControl: false,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 8,
    capabilities: ['text-to-video', 'image-to-video'],
  },
  {
    id: 'hailuo',
    name: 'Hailuo',
    provider: 'hailuo',
    type: 'video',
    tier: 'quality',
    badge: 'Native Audio',
    description: 'Hailuo — excellent for dynamic motion with native audio generation.',
    keyFeatures: ['Native audio', 'Dynamic motion', 'Smooth transitions', '6s clips'],
    maxDuration: 6,
    nativeAudio: true,
    firstFrame: true,
    motionControl: false,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 10,
    capabilities: ['text-to-video', 'image-to-video', 'native-audio'],
  },
  {
    id: 'seedance',
    name: 'Seedance',
    provider: 'seedance',
    type: 'video',
    tier: 'quality',
    badge: 'Lip Sync',
    description: 'Seedance — optimized for human subjects with lip sync support.',
    keyFeatures: ['Lip sync', 'Human motion', 'Facial consistency', '5s clips'],
    maxDuration: 5,
    nativeAudio: false,
    lipSync: true,
    firstFrame: true,
    motionControl: false,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: false,
    credits: 12,
    capabilities: ['image-to-video', 'lip-sync'],
  },
  {
    id: 'runway',
    name: 'Runway Gen-4',
    provider: 'runway',
    type: 'video',
    tier: 'ultra',
    description: 'Runway Gen-4 — cinematic quality with advanced motion control.',
    keyFeatures: ['Cinematic quality', 'Motion control', 'First+Last frame', '10s clips'],
    maxDuration: 10,
    nativeAudio: false,
    firstFrame: true,
    lastFrame: true,
    motionControl: true,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 20,
    capabilities: ['text-to-video', 'image-to-video', 'motion-control'],
  },
  {
    id: 'classic-fast',
    name: 'Classic Fast',
    provider: 'fal',
    type: 'video',
    tier: 'fast',
    description: 'Quick video generation for storyboarding and concept testing.',
    keyFeatures: ['Fast generation', 'Low cost', 'Concept testing', '3s clips'],
    maxDuration: 3,
    firstFrame: false,
    motionControl: false,
    realisticOutput: false,
    imageToVideo: false,
    textToVideo: true,
    credits: 3,
    capabilities: ['text-to-video'],
  },
  {
    id: 'classic',
    name: 'Classic',
    provider: 'fal',
    type: 'video',
    tier: 'quality',
    description: 'Reliable classic model for general-purpose video generation.',
    keyFeatures: ['Reliable', 'General purpose', 'Balanced', '5s clips'],
    maxDuration: 5,
    firstFrame: true,
    motionControl: false,
    realisticOutput: true,
    imageToVideo: true,
    textToVideo: true,
    credits: 6,
    capabilities: ['text-to-video', 'image-to-video'],
  },
];

// ─── AUDIO / MUSIC MODELS ─────────────────────────────────────────────────────

export const AUDIO_MODELS: CraftModel[] = [
  {
    id: 'elevenlabs-v3',
    name: 'ElevenLabs v3',
    provider: 'elevenlabs',
    type: 'voice',
    tier: 'ultra',
    badge: 'Recommended',
    description: 'Best-in-class voice synthesis with emotion and multilingual support.',
    keyFeatures: ['Most natural voices', 'Emotion control', '29 languages', 'Voice cloning'],
    credits: 8,
    isRecommended: true,
    capabilities: ['text-to-speech', 'voice-cloning', 'emotion-control'],
  },
  {
    id: 'suno-v4',
    name: 'Suno v4',
    provider: 'suno',
    type: 'music',
    tier: 'ultra',
    badge: 'Best Music',
    description: 'Full music generation with lyrics, vocals, and arrangement.',
    keyFeatures: ['Full songs', 'Lyrics + vocals', 'Genre control', '4 min output'],
    maxDuration: 240,
    credits: 10,
    isRecommended: true,
    capabilities: ['text-to-music', 'vocal-generation'],
  },
];

// ─── STYLE PRESETS ─────────────────────────────────────────────────────────────

export interface StylePreset {
  id: string;
  name: string;
  description: string;
  tags: string[];
  thumbnail?: string;
  isRecommended?: boolean;
  applicableTo: ('image' | 'video' | 'social' | 'product' | 'photography')[];
}

export const STYLE_PRESETS: StylePreset[] = [
  { id: 'cinematic-noir', name: 'Cinematic Noir', description: 'High contrast black and white, dramatic shadows, editorial depth', tags: ['Monochrome', 'Dramatic', 'Film'], isRecommended: true, applicableTo: ['image', 'video', 'photography'] },
  { id: 'editorial-clean', name: 'Editorial Clean', description: 'Minimal, white background, product-forward, luxury feel', tags: ['Minimal', 'White', 'Luxury'], applicableTo: ['image', 'product', 'photography', 'social'] },
  { id: 'golden-hour', name: 'Golden Hour', description: 'Warm amber tones, soft directional light, organic warmth', tags: ['Warm', 'Natural', 'Organic'], applicableTo: ['image', 'video', 'photography', 'social'] },
  { id: 'ink-illustration', name: 'Ink Illustration', description: 'Hand-drawn ink style, graphic, editorial cartoon quality', tags: ['Illustrated', 'Ink', 'Graphic'], applicableTo: ['image', 'video', 'social'] },
  { id: 'documentary', name: 'Documentary', description: 'Real, unposed, authentic moment capture, natural light', tags: ['Authentic', 'Real', 'Natural'], applicableTo: ['image', 'video', 'photography'] },
  { id: 'fashion-dark', name: 'Fashion Dark', description: 'High-fashion aesthetic, moody palette, editorial pose', tags: ['Fashion', 'Moody', 'Editorial'], applicableTo: ['image', 'photography', 'social', 'product'] },
  { id: 'tech-minimal', name: 'Tech Minimal', description: 'Clean surfaces, geometric, futuristic minimalism', tags: ['Tech', 'Geometric', 'Minimal'], applicableTo: ['image', 'product', 'social'] },
  { id: 'hyperreal', name: 'Hyperreal', description: 'Photographic perfection, beyond reality, maximum detail', tags: ['Photorealistic', 'Detail', 'Perfect'], applicableTo: ['image', 'product', 'photography'] },
  { id: 'anime-cinematic', name: 'Anime Cinematic', description: 'Japanese animation quality, cel-shaded, dramatic angles', tags: ['Anime', 'Stylized', 'Dramatic'], applicableTo: ['image', 'video'] },
  { id: 'brand-story', name: 'Brand Story', description: 'Consistent brand world, aspirational lifestyle, values-forward', tags: ['Brand', 'Lifestyle', 'Story'], applicableTo: ['image', 'video', 'social', 'product'] },
];

// ─── ALL MODELS MAP ────────────────────────────────────────────────────────────

export const ALL_MODELS = {
  image: IMAGE_MODELS,
  video: VIDEO_MODELS,
  audio: AUDIO_MODELS,
};

export function getModelById(id: string): CraftModel | undefined {
  return [...IMAGE_MODELS, ...VIDEO_MODELS, ...AUDIO_MODELS].find(m => m.id === id);
}

export function getRecommendedModel(type: ModelType): CraftModel | undefined {
  const models = type === 'image' ? IMAGE_MODELS : type === 'video' ? VIDEO_MODELS : AUDIO_MODELS;
  return models.find(m => m.isRecommended) ?? models[0];
}
